<?php
use App\helpers\HtmlHelper as Html;

?>
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Learn yaf</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <?php
            $items = [
                ['label' => 'Home', 'url' => ['/index/index']],
                ['label' => 'User', 'url' => ['/user/index']],
                ['label' => 'DropDown', 'url' => '#', 'items'=>[
                    ['label' => 'Action', 'url' => '#'],
                    ['label' => 'Another action', 'url' => '#'],
                    '<li class="divider"></li>',
                    '<li class="dropdown-header">Dropdown Header</li>',
                    ['label' => 'Separated link', 'url' => '#'],
                ]]
            ];
            echo Html::navbar($items);

            if (\Yaf\Registry::get('WebUser')->getIsGuest()) {
                $items = [
                    ['label' => 'Register', 'url' => ['/auth/register']],
                    ['label' => 'Login', 'url' => ['/auth/login']],
                ];
            } else {
                $items = [
                    ['label' => 'Logout ('.\Yaf\Registry::get('WebUser')->getIdentity()->username.')', 'url' => Url::toRoute('/auth/logout')],
                ];
            }
            echo Html::navbar($items, ['containerClass' => 'nav navbar-nav navbar-right']);
            ?>
        </div><!--/.nav-collapse -->
    </div>
</nav>