<?php
/**
 * Created by PhpStorm.
 * User: guoxiaosong
 * Date: 15/6/12
 * Time: 上午10:50
 */
?>
<form method="post" action="/auth/login">
    <div class="form-group<?php  echo ($form->hasErrors('username'))?" has-error":"";?>">
        <label for="username">User name:</label>
        <input type="text" class="form-control" id="username" name="username" value="<?php echo $form->username; ?>"
               placeholder="User name" />
        <?php if ($form->hasErrors('username')) :?>
            <p class="help-block help-block-error"><?php echo $form->getFirstError('username'); ?></p>
        <?php endif; ?>
    </div>

    <div class="form-group<?php echo ($form->hasErrors('password'))?" has-error":"";?>">
        <label for="password">Password:</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Password" />
        <?php if ($form->hasErrors('password')) :?>
            <p class="help-block help-block-error"><?php echo $form->getFirstError('password'); ?></p>
        <?php endif; ?>
    </div>

    <div class="checkbox<?php echo ($form->hasErrors('rememberMe'))?" has-error":"";?>">
        <label><input type="checkbox" name="rememberMe" value="1" <?php echo ($form->rememberMe) ? "checked='checked'":
                "";?>> Remember
            Me</label>
        <?php if ($form->hasErrors('rememberMe')) :?>
            <p class="help-block help-block-error"><?php echo $form->getFirstError('rememberMe'); ?></p>
        <?php endif; ?>
    </div>

    <div class="form-group">
        <button class="btn btn-default" type="submit">Login</button>
    </div>
</form>