<form method="post">
    <div class="form-group">
        <label for="username">User name:</label>
        <input type="text" class="form-control" id="username" name="username" value="<?php echo $form->username; ?>"
        placeholder="User name" />
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
        <input type="text" class="form-control" id="password" name="password" placeholder="Password" />
    </div>
    <div class="form-group">
        <label for="repeatPassword">Repeat password:</label>
        <input type="text" class="form-control" id="repeatPassword" name="repeatPassword"
               placeholder="Repeat password" />
    </div>
    <div class="form-group">
        <button class="btn btn-default" type="submit">Register</button>
    </div>
</form>