<?php
/**
 * Created by PhpStorm.
 * User: guoxiaosong
 * Date: 15/6/12
 * Time: 上午10:50
 */
?>
<form method="post" action="/auth/register">
    <div class="form-group <?php echo ($form->hasErrors('username'))?"has-error":"";?>">
        <label for="username">User name:</label>
        <input type="text" class="form-control" id="username" name="username" value="<?php echo $form->username; ?>"
        placeholder="User name" />
        <?php if ($form->hasErrors('username')) :?>
            <p class="help-block help-block-error"><?php echo $form->getFirstError('username'); ?></p>
        <?php endif; ?>
    </div>
    <div class="form-group <?php echo ($form->hasErrors('password'))?"has-error":"";?>">
        <label for="password">Password:</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Password" />
        <?php if ($form->hasErrors('password')) :?>
            <p class="help-block help-block-error"><?php echo $form->getFirstError('password'); ?></p>
        <?php endif; ?>
    </div>
    <div class="form-group <?php echo ($form->hasErrors('repeatPassword'))?"has-error":"";?>">
        <label for="repeatPassword">Repeat password:</label>
        <input type="password" class="form-control" id="repeatPassword" name="repeatPassword"
               placeholder="Repeat password" />
        <?php if ($form->hasErrors('repeatPassword')) :?>
            <p class="help-block help-block-error"><?php echo $form->getFirstError('repeatPassword'); ?></p>
        <?php endif; ?>
    </div>
    <div class="form-group">
        <button class="btn btn-default" type="submit">Register</button>
    </div>
</form>