<?php
/**
 * Created by PhpStorm.
 * User: guoxiaosong
 * Date: 15/6/19
 * Time: 下午1:42
 */
use App\Helpers\UrlHelper as Url;

?>
<h2>Hotel Lists</h2>
<?php echo $models->render(); ?>
<table class="table table-hover table-condensed">
    <thead>
    <tr>
        <th class="col-md-1">酒店编号</th>
        <th>中文名称</th>
        <th>英文名称</th>
        <th class="col-md-1">国家</th>
        <th>位置</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($models as $model): ?>
        <tr>
            <th><?php echo $model->hotel_id; ?></th>
            <th><?php echo '<a href="'.Url::toRoute(['/hotel/view', 'id' => $model->id]).'" data-toggle="tooltip"
             title="'.$model->location.'">'. $model->name .'</a>';
                ?></th>
            <th><?php echo $model->ename; ?></th>
            <th><?php echo $model->country; ?></th>
            <th><?php echo $model->location; ?></th>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php echo $models->render(); ?>